### PR TITLE
Fix for possible race condition. Fixes #50

### LINKED ISSUE #50: Updating plugin resets Z_DATA
Whenever I run `fisher u`, my Z_DATA is reset and I lose all history.
Is this a bug? If not, is there a way to go around that without having to manually backup than restore before every fisher update?

### PR DESCRIPTION
**Pull request by externl**

### CODE REVIEW

**Comment by externl** [comment]
This fixes the issue where `$Z_DATA` can be corrupted by a race condition. It is still possible for some  minimal data loss, but there should be no corruption. I don't think implementing a lock in fish is worth it.

**Comment by jethrokuan** [comment]
Thanks for figuring out the cause. This was introduced in https://github.com/fisherman/z/commit/c323913826a90b7ccc82a9c4c0297b1544b560fa for https://github.com/fisherman/z/issues/26. Do you have a good way of maintaining file ownership metadata?

**Comment by externl** [comment]
What about something like:
 ```
set -l tmpfile (mktemp -u $Z_DATA.XXXXXX)

cp -p $Z_DATA $tmpfile
command awk -v path="$PWD" -v now=(date +%s) -F "|" -f $path/zadd.awk $Z_DATA ^ /dev/null > $tmpfile

command mv $tmpfile $Z_DATA
or command rm $tmpfile
```

Get a temp file path from `mktemp` but don't create the file. Copy with `-p` to preserve ownership. Then overwrite it and move it back into $Z_DATA.

**Comment by jethrokuan** [comment]
@externl how about this:

https://askubuntu.com/questions/56792/how-to-copy-only-file-attributes-metadata-without-actual-content-of-the-file

make a tempfile, and use the --reference attribute to copy attributes to the new file?

**Comment by externl** [comment]
Doesn't work on macOS.
```
❯ chown --reference=data data.tmp
chown: illegal option -- -
```

**Comment by jethrokuan** [comment]
let's go with rupa's approach. This ownership issue doesn't affect most people, and when it does, at least there's a way for them to work around it.

**Comment by externl** [comment]
Ok, I'll update my PR.

**Comment by jethrokuan** [comment]
Awesome, thanks!

**Pull request merged**
